# Install, Importing Modules, and Loading Data


## 1 Python Modules, Packages and Import Data From Moldules

**Modules** are *Python* files that contain functions and variables for a specific purpose. You can access these modules and make reuse of their code to solve your problem. A *Package* is a collection of such modules in directories that give a package hierarchy.

<img src="https://www.ikea.com/ca/en/images/products/bygglek-201-piece-lego-r-brick-set-mixed-colors__0915518_pe784785_s5.jpg" width="400" height="400"/>

One advantage of the *Anaconda distribution* and *Google Colab* is that it already comes with a number of built-in modules, so that we do not need to spend time downloading and managing these files. However, if you want to add a new package, you can use the either *pip* or *conda* command line tool that comes with *Anaconda*.


### 1.1 pip install modulename

To access **Terminal** commands in Jupyter notebook, we can use the magic character `!`.

Following the `!`, type `pip install modulename` or `conda install modulename` to install that module to the root environment of Anaconda or Google Colab. The difference between *pip* and *conda* is that they download Modules from different cloud repositories.

Let's install the **wooldridge** package by type the following command in a new code cell

`pip install wooldridge`

In [ ]:
! pip install wooldridge

Requirement already satisfied: wooldridge in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from wooldridge) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->wooldridge) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->wooldridge) (1.17.0)

Now, we can import this module and call it `woo`

In [ ]:
import wooldridge as woo

Don't forget to execute the code

Coding is never as intuitive as a graphical user interface. We do not have drop-down menus or buttons with names on it. Instead, we need to go the old-fashioned way - reading a manual (a.k.a as **API** or **documentation**). Google "python wooldridge" to find the following [wooldridge documentation](https://pypi.org/project/wooldridge/). It will instruct on how to use this Module.

In [ ]:
# Here I want to show you another way to add comments to your code.
# Instead of using the Markdown mode in a Jupyter notebook, you can use # to prefix any comments in Python

# import a dataset called 'wage1' and assign it to a variable called wage1
# show the first five rows of this dataset
wage1 = woo.data("wage1")
wage1.head()

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,1,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,1,0,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4

In [ ]:
# wage1.to_csv("wage1.csv") # This line saves the data to a csv file

### 1.2 A soft introduction of object oriented programming

Python is an object-oriented programming language, which means our coding logic is based on **objects**. Object in Python is a similar concept as the real-world object. For example, this notebook is an object, the blackboard is an object, you computer is an object. Similarly, the wage1 dataset is an object, the number "1" is an object, and the "Hello World" string is an object. We can categorize objects into different **classes**, so that objects in the same class should share some common features. The documentation of that class would document the **attributes** (properties such as name, length, size ..) and **methods** (what it can do, such as go(), turn(), move()) of all objects that belong to that class.

We noticed that *wage1* is a pandas DataFrame (i.e. this object belongs to the DataFrame class). To see what it can do, we need to look up the [pandas DataFrame documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

Try to locate the `head()` method.

In the documentation, we find that the head method takes one *parameter* - n, and returns the same type as the caller -  a DataFrame.

To use this parameter, we can either pass an argument `5` to the parameter name `n` - `wage1.head(n=5)` or we can ignore both the parameter name and the `=` sign.

In [ ]:
wage1.head(5)

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,1,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,1,0,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4

This method returns the first "5" (the value of the parameter) rows of the wage1 dataset. We will continue to discuss the descriptive data analysis with pandas DataFrame in the next chapter. But for now let's focus on how to load data from other types of files.

Before loading new data, let's delet the wage1 variable to free up some memory. In Python, you can delete any object using the `del` keyword.

In [ ]:
del wage1

## 2 Import Data From Different Data Files

Besides the example datasets from the wooldridge module, we would encounter a lot of common data files in our daily workflow. Common files name extensions for these data files are *RAW*, *CSV* or *TXT*. Knowing how to import these data files is a critical skill for a data analyst.

### 2.1 Read .csv file

The **pandas** module provides methods for reading various data files.

For example, we can use `pandas.read_csv()` to read files with the `.csv` extension. you can find its [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) by googling "pandas read csv" .

The pandas.read_csv() *Method* takes more than one **parameters**. These parameters are the options for this method. Values passed to these parameters are called **arguments**. Multiple arguments are separated by `,`. In a document, values following the `=` after the parameter names, if any, are the default values.

Let's read `wage1.csv` with the default arguments.

In [ ]:
import pandas as pd
wage1=pd.read_csv("wage1.csv")

"""
Another way to leave comments! Three quotations give you a comment block!

Note the first parameter "filepath_or_buffer=" is not spelled out. When arguments provided
in the documented order, the parameter names and the = signs can be ignored.
"""

'\nAnother way to leave comments! Three quotations give you a comment block!\n\nNote the first parameter "filepath_or_buffer=" is not spelled out. When arguments provided\nin the documented order, the parameter names and the = signs can be ignored.\n'

### 2.2 Pandas DataFrame

pandas **DataFrame** is the most commenly used class (user-defined data type) to store data. The first column of a DataFrame is called **index**, and columns of a DataFrame are of **Series** data type.

To extract column(s) from a DataFrame, the easiest way is to use the **index bracket** `[]`.

In [ ]:
print(wage1.columns)

Index(['Unnamed: 0', 'wage', 'educ', 'exper', 'tenure', 'nonwhite', 'female',
       'married', 'numdep', 'smsa', 'northcen', 'south', 'west', 'construc',
       'ndurman', 'trcommpu', 'trade', 'services', 'profserv', 'profocc',
       'clerocc', 'servocc', 'lwage', 'expersq', 'tenursq'],
      dtype='object')

In [ ]:
wage1["wage"]

0       3.10
1       3.24
2       3.00
3       6.00
4       5.30
       ...
521    15.00
522     2.27
523     4.67
524    11.56
525     3.50
Name: wage, Length: 526, dtype: float64

In [ ]:
# The data type of a column is a Series
type(wage1["wage"])

pandas.core.series.Series

If you want to extract more than one columns, pass a **list** into the index bracket `[]`.

In [ ]:
wage1[["wage","educ"]]

      wage  educ
0     3.10    11
1     3.24    12
2     3.00    11
3     6.00     8
4     5.30    12
..     ...   ...
521  15.00    16
522   2.27    10
523   4.67    15
524  11.56    16
525   3.50    14

[526 rows x 2 columns]

Before we continue, let's "save" the two columns to a variable so that we can reuse it later.

In [ ]:
df = wage1[["wage","educ"]]
print(df)

      wage  educ
0     3.10    11
1     3.24    12
2     3.00    11
3     6.00     8
4     5.30    12
..     ...   ...
521  15.00    16
522   2.27    10
523   4.67    15
524  11.56    16
525   3.50    14

[526 rows x 2 columns]

### 2.3 Read .txt file

Let's import another .txt data file. Before importing, you can navigate to the `wine.txt` file in side bar and double click to preview the file.

From the preview, we find that this data file provides headers in the first row, and indexes in the first column. Let's pass `0` to the `index_col` parameter. We do not wrap `0` with quation marks because the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_table.html) says that the `index_col` parameters accept an **int**.

In [ ]:
# import txt with pandas:
wine = pd.read_table("wine.txt",index_col=0)
wine.head()

     country  alcohol  deaths  heart      liver
0  Australia      2.5     785    211  15.300000
1    Austria      3.9     863    167  45.599998
2   Belg/Lux      2.9     883    131  20.700001
3     Canada      2.4     793    191  16.400000
4    Denmark      2.9     971    220  23.900000

>**Exercise** \
    1. read in wine.txt and assign it to a variable called df2 \
    2. display the first 10 lines \
    3. extract the country and alcohol column, then assign the result to df2

DataFrame also allows you to select a range of rows and columns using **slice object**

In [ ]:
# if you prefer to refer to rows and columns with indeces (numbers), use iloc[]
# inside the [], type the range of row indeces of your choice, then a comma, follwed by the range of column indeces
# for example

wine.iloc[0:10, 0:2]

# returns: rows starting at index 0 and stopping right before index 10 (10 not included)
# columns: 0 and 1 (2 not included)

     country  alcohol
0  Australia      2.5
1    Austria      3.9
2   Belg/Lux      2.9
3     Canada      2.4
4    Denmark      2.9
5    Finland      0.8
6     France      9.1
7    Iceland      0.8
8    Ireland      0.7
9     Israel      0.6

In [ ]:
# you can also count the index backward

wine.iloc[:, -2:]

# here we extract the last 2 rows.
# -2 means second from the last, : followed by no value means 'to the last'
# the first ':' means 'from first to last'.

    heart      liver
0     211  15.300000
1     167  45.599998
2     131  20.700001
3     191  16.400000
4     220  23.900000
5     297  19.000000
6      71  37.900002
7     211  11.200000
8     300   6.500000
9     183  13.700000
10    107  42.200001
11     36  23.200001
12    167   9.200000
13    266   7.700000
14    227  12.200000
15     86  36.400002
16    207  11.200000
17    115  20.299999
18    285  10.300000
19    199  22.100000
20    172  36.700001

In [ ]:
wine.iloc[[0,2,4],:]
# you can also skip rows or columns by giving a list of indeces
# in this example, we extract row with indeces 0,2, and 4, and we keep all the columns.

     country  alcohol  deaths  heart      liver
0  Australia      2.5     785    211  15.300000
2   Belg/Lux      2.9     883    131  20.700001
4    Denmark      2.9     971    220  23.900000

In [ ]:
n = wine.iloc[3,2]
print(n)

793

In [ ]:
# when you slice to a single value, it turns into a primitive DataType
type(n)

numpy.int64

> **Exercise** \
    1. Extract rows 2 to 5 of columns *country* and *deaths* \
    2. Extract the first 5 rows of all columns \
    3. Extract the last 3 rows of the *liver* column

  Sometimes, it is easier to refer to columns and rows by their names instead of indeces. To do this, we can use `.loc[]`.

In [ ]:
wine.loc[0:2,["country","deaths"]]

# Note that the row names and indeces are the same in this dataset

     country  deaths
0  Australia     785
1    Austria     863
2   Belg/Lux     883

## 3 Import Data From API

We can also load data not locally stored on your computer. To do this, simply pass a URL to the `filepath_or_buffer` parameter.

In [ ]:
import pandas as pd

In [ ]:
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv"
df = pd.read_csv(url)


Often times, the datafiles are not directly hosted online, instead we need to request data through **Application Programming Interfaces (API)**. APIs can be viewd as a "menu" offered by a data provider. It tells us what data they have and how to retrieve them.

A module called **pandas-datareader** makes it straight forward to query a handful (but limited) of online data.

It is not part of the Anaconda distribution so we need to install this module first. Create a new cell and type `!pip install pandas-datareader`. Your computer will download this module from PyPI and save it at the Anaconda root environment.

In [ ]:
!pip install pandas-datareader

Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.12/dist-packages (0.10.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pandas-datareader) (6.0.2)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.12/dist-packages (from pandas-datareader) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pandas-datareader) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas-datareader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas-datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.23->pandas-datareader) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas-datareader) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas-datareader) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas-datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pandas-datareader) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.17.0)

The following script demonstrates the workflow of importing stock data of Ford Motor Company. Read this [documentation](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#fred) to see more about how to use pandas-datareader.

For example we can read GDP data from FRED:

In [ ]:
import pandas_datareader as pdr

f=pdr.data.DataReader('GDP', 'fred', "2023-1-1", "2024-1-1")
f.head()

                  GDP
DATE
2023-01-01  27216.445
2023-04-01  27530.055
2023-07-01  28074.846
2023-10-01  28424.722
2024-01-01  28708.161

In [ ]:
# you can replace the string date with Python date object
from datetime import date
print(date.today())

2026-01-22

A more general way of accessing online data is to use a module called [**requests**](https://pypi.org/project/requests/). requests allows you to send HTTP/1.1 requests and returns its response. To avoid overburdening data providers, we do not provide examples in this tutorial. Interested student can find examples from the requests online documentation.

In [ ]:
import requests